---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-app
spec:
  project: default
  sources:
    - chart: cert-manager
      repoURL: https://charts.jetstack.io
      targetRevision: 1.17.2
      helm:
        releaseName: cert-manager
        valuesObject:
          global:
            leaderElection:
              namespace: cert-manager
          crds:
            enabled: true
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true # Big CRDs.
  ignoreDifferences: []
