apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: edgecdnx
spec:
  acme:
    email: tbo@tbotech.sk
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: control-k8s-edgecdnx-com-key
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx