apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: edgecdnx
spec:
  acme:
    email: tbo@tbotech.sk
    server: http://vault.vault.svc.cluster.local:8200/v1/pki_int/acme/directory
    privateKeySecretRef:
      name: control-k8s-edgecdnx-com-key
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx