apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: edgecdnx
spec:
  project: default
  source:
    repoURL: ssh://git@github.com/EdgeCDN-X/bootstrap.git
    targetRevision: HEAD
    path: edgecdnx-resources
  destination:
    server: https://kubernetes.default.svc
    namespace: edgecdnx
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      allowEmpty: true
