---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-origin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-origin
  template:
    metadata:
      labels:
        app: test-origin
    spec:
      containers:
        - name: test-origin
          image: fr6nco/edgecdnx-test-origin:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: test-origin-service
spec:
  selector:
    app: test-origin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-origin-ingress
  annotations:
    cert-manager.io/cluster-issuer: control.k8s.edgecdnx.com
spec:
  ingressClassName: nginx
  rules:
    - host: origin.control.k8s.edgecdnx.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: test-origin-service
                port:
                  number: 80\
  tls:
    - hosts:
        - origin.control.k8s.edgecdnx.com
      secretName: origin-control-k8s-edgecdnx-com-tls