---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: edgecdnx-cache
  namespace: argocd
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
    - clusters:
        values:
          chart: ingress-nginx
          chartVersion: 4.12.1
          chartRepository: https://kubernetes.github.io/ingress-nginx
          namespace: edgecdnx-cache
          cache: ssd
          path: /var/cache/ssd
        selector:
          matchExpressions:
            - key: edgecdnx.com/caching
              operator: In
              values:
                - "true"
                - "yes"
            - key: edgecdnx.com/tier
              operator: In
              values:
                - edge
  template:
    metadata:
      name: edgecdnx-cache-{{ .values.cache }}-{{ index .metadata.labels "edgecdnx.com/location" }}-{{ .values.tier }}
    spec:
      project: default
      sources:
        - chart: "{{ .values.chart }}"
          repoURL: "{{ .values.chartRepository }}"
          targetRevision: "{{ .values.chartVersion }}"
          helm:
            releaseName: ingress-nginx-{{ .values.cache }}
            ignoreMissingValueFiles: true
            valuesObject:
              controller:
                metrics:
                  enabled: false
                  serviceMonitor:
                    enabled: false
                    additionalLabels:
                      release: prometheus-stack
                allowSnippetAnnotations: true
                ingressClassResource:
                  enabled: true
                  default: false
                  name: "edgecdnx-cache-{{ .values.cache }}"
                  controllerValue: "edgecdnx.com/cache-{{ .values.cache }}"
                service:
                  enabled: false
                hostPort:
                  enabled: true
                kind: DaemonSet
                nodeSelector:
                  edgecdnx.com/cache: "{{ .values.cache }}"
                extraVolumes:
                  - name: nginx-cache
                    hostPath:
                      path: "{{ .values.path }}"
                      type: Directory
                extraVolumeMounts:
                  - name: nginx-cache
                    mountPath: "{{ .values.path }}"
                config:
                  proxy-buffering: "on"
                  annotations-risk-level: "Critical"
                  http-snippet: |
                    proxy_cache_path {{ .values.path }} levels=1:2 keys_zone=cdn_cache:100m inactive=10080m use_temp_path=off;
      destination:
        namespace: "{{ .values.namespace }}"
        server: "{{ .server }}"
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true # Big CRDs.
      ignoreDifferences: []
