---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: edgecdnx-routing
  namespace: argocd
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
    - matrix:
        generators:
          - clusters:
              flatList: true
              selector:
                matchExpressions:
                  - key: edgecdnx.com/routing
                    operator: In
                    values:
                      - "true"
                      - "yes"
          - clusters:
              values:
                chart: coredns
                chartVersion: 1.43.0
                chartRepository: https://coredns.github.io/helm
                namespace: edgecdnx-routing
              selector:
                matchExpressions:
                  - key: edgecdnx.com/routing
                    operator: In
                    values:
                      - "true"
                      - "yes"
  template:
    metadata:
      name: edgecdnx-coredns-{{ index .metadata.labels "edgecdnx.com/location" }}
    spec:
      project: default
      sources:
        - chart: "{{ .values.chart }}"
          repoURL: "{{ .values.chartRepository }}"
          targetRevision: "{{ .values.chartVersion }}"
          helm:
            releaseName: edgecdnx-coredns
            ignoreMissingValueFiles: true
            valuesObject:
              image:
                repository: fr6nco/coredns
                tag: latest
                pullPolicy: Always
              serviceType: LoadBalancer
              isClusterService: false
              replicaCount: 2
              servers:
                - port: 53
                  plugins:
                    - name: ready
                    - name: debug
                    - name: metadata
                    - name: health
                      configBlock: |-
                        lameduck 10s
                    - name: file 
                      parameters: /etc/coredns/cdn.edgecdnx.com.zone cdn.edgecdnx.com
                    - name: edgecdnxservices
                      parameters: edgecdnx-routing
                    - name: edgecdnxprefixlist
                      parameters: edgecdnx-routing
                    - name: geoip
                      parameters: /etc/edgecdnx/geolookup/GeoLite2-City.mmdb
                      configBlock: |
                        edns-subnet
                    - name: edgecdnxgeolookup
                      parameters: edgecdnx-routing
                  zones:
                  - zone: "."
              zoneFiles:
                - filename: cdn.edgecdnx.com.zone
                  contents: |
                    $ORIGIN cdn.edgecdnx.com.
                    $TTL 300

                    @   IN  SOA     {{- range .clusters -}}{{ if eq .name $.name }} ns{{ index .metadata.annotations "edgecdnx.com/ns" }}{{ end -}}{{- end -}}.cdn.edgecdnx.com. noc.edgecdnx.com. (
                            2025060400  ;Serial
                            7200        ;Refresh
                            3600        ;Retry
                            1209600     ;Expire
                            3600        ;Negative response caching TTL
                    )

                    {{- range .clusters }}
                                IN           NS              ns{{ index .metadata.annotations "edgecdnx.com/ns" }}.cdn.edgecdnx.com.
                    ns{{ index .metadata.annotations "edgecdnx.com/ns" }}         IN           A               {{ index .metadata.annotations "edgecdnx.com/public-ip" }}
                    {{- end }}
              initContainers:
                - name: edgecdnx-mmdb-init
                  image: curlimages/curl:8.14.1
                  volumeMounts:
                    - name: geolookup-mmdb
                      mountPath: /etc/edgecdnx/geolookup
                  command:
                    - sh
                    - -c
                    - |
                      curl -L https://share.tbotech.sk/api/shares/7aAqdIUO/files/4e046472-f00d-4275-be7b-b5228ff200ce -o /etc/edgecdnx/geolookup/GeoLite2-City.mmdb
              extraVolumes:
                - name: geolookup-mmdb
                  emptyDir: {}
              extraVolumeMounts:
                - name: geolookup-mmdb
                  mountPath: /etc/edgecdnx/geolookup
        - chart: coredns-rbac
          repoURL: https://edgecdn-x.github.io/helm-charts
          targetRevision: 0.1.1
          helm:
            releaseName: edgecdnx-coredns-rbac
            ignoreMissingValueFiles: true
            valuesObject:
              serviceAccount: default
      destination:
        namespace: "{{ .values.namespace }}"
        server: "{{ .server }}"
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true # Big CRDs.
      ignoreDifferences: []
