---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: metallb-routing
  namespace: argocd
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
    - clusters:
        values:
          chart: metallb
          chartVersion: 0.14.9
          chartRepository: https://metallb.github.io/metallb
          namespace: metallb-system
          chartConfig: metallb-config
          chartConfigVersion: 0.1.0
          chartConfigRepository: https://edgecdn-x.github.io/helm-charts
        selector:
          matchExpressions:
            - key: edgecdnx.com/routing
              operator: In
              values:
                - "true"
                - "yes"
  template:
    metadata:
      name: metallb-{{ index .metadata.labels "edgecdnx.com/location" }}
    spec:
      project: default
      sources:
        - chart: "{{ .values.chart }}"
          repoURL: "{{ .values.chartRepository }}"
          targetRevision: "{{ .values.chartVersion }}"
          helm:
            releaseName: metallb
            ignoreMissingValueFiles: true
            valuesObject:
              speaker:
                ignoreExcludeLB: true
        - chart: "{{ .values.chartConfig }}"
          repoURL: "{{ .values.chartConfigVersion }}"
          targetRevision: "{{ .values.chartConfigVersion }}"
          helm:
            releaseName: metallb-config
            ignoreMissingValueFiles: true
            valuesObject:
              addressPools:
                - name: pool1
                  addresses:
                    - '{{ index .metadata.annotations "metallb-pool" }}'
                  l2advertisement: true
      destination:
        namespace: "{{ .values.namespace }}"
        server: "{{ .server }}"
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true # Big CRDs.
      ignoreDifferences: []
