apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-s3-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-s3-gateway
  template:
    metadata:
      labels:
        app: nginx-s3-gateway
    spec:
      containers:
        - name: nginx-s3-gateway
          image: nginxinc/nginx-s3-gateway:latest-njs-oss-20250709
          ports:
            - containerPort: 80
          env:
            - name: S3_BUCKET_NAME
              value: "numeroart"
            - name: S3_REGION
              value: "fra1"
            - name: S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3-gateway-credentials
                  key: S3_ACCESS_KEY_ID
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-gateway-credentials
                  key: S3_SECRET_KEY
            - name: S3_SERVER
              value: digitaloceanspaces.com
            - name: S3_SERVER_PORT
              value: "443"
            - name: S3_SERVER_PROTO
              value: "https"
            - name: S3_STLE
              value: "virtual"
            - name: AWS_SIGS_VERSION
              value: "4"